### PR TITLE
Handle quotes in error message for invalid token

### PR DESCRIPTION
**Pull request by Johann-S**
Hi :)

First of all thanks for Buttercup, it's an awesome tool!

I try to fix this issue: https://github.com/buttercup/buttercup-desktop/issues/1188

### CODE REVIEW

**Comment by rapinto** [comment]
Maybe you should handle both cases ? I wouldn't be surprised if Google remove the "" from the url.

**Comment by Johann-S** [comment]
Seems like: https://github.com/buttercup/googledrive-client/commit/4675fb2ae88267d5165a77b8ae6fad47cb3672f3 by @perry-mitchell already fixed that

**Comment by perry-mitchell** [comment]
Sorry I missed this! Was heads-down debugging the issue..

**Comment by Johann-S** [comment]
it's ok, it's happens 😉 thx for the quick (and better) fix!

**Pull request closed without merging**
